# Generated by Django 4.1.5 on 2023-01-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=2.5)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_article', models.CharField(default='новость', max_length=20)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('title_news', models.CharField(default='Сенсация', max_length=50)),
                ('text_news', models.TextField(default='Когда политики всех стран наконец то договорятся о мире?')),
                ('rating', models.FloatField(default=2.5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.author')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.category')),
                ('post_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category_com',
            field=models.ManyToManyField(through='News.PostCategory', to='News.category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='Хорошая новость')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(default=2.5)),
                ('post_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.post')),
                ('user_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.user')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='user_com',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='News.user'),
        ),
    ]
