# Generated by Django 4.1.5 on 2023-01-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='_rating',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='post',
            name='_rating',
            field=models.FloatField(default=2.5),
        ),
    ]
