# Generated by Django 4.1.5 on 2023-01-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_remove_comment_rating_remove_post_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_rating',
            new_name='rating',
        ),
    ]
