# Generated by Django 4.1.5 on 2023-01-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_rename__rating_comment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_com',
            field=models.ManyToManyField(related_name='news', through='News.PostCategory', to='News.category'),
        ),
    ]
