# Generated by Django 4.1.5 on 2023-02-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_alter_post_category_com'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time_in',
            new_name='time',
        ),
    ]
