# Generated by Django 4.1.5 on 2023-02-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_rename_time_in_post_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='time_in',
        ),
    ]
