# Generated by Django 4.1.5 on 2023-02-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_rename_time_post_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_news',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_news',
            field=models.CharField(max_length=50),
        ),
    ]
