# Generated by Django 4.1.5 on 2023-02-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_alter_post_text_news_alter_post_title_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(to='News.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='news_article',
            field=models.CharField(max_length=20),
        ),
    ]
