# Generated by Django 4.1.5 on 2023-02-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_category_subscribers_alter_post_news_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='categories', to='News.user'),
        ),
    ]
